# Generated by Django 4.2.9 on 2024-02-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_category_note_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
